name: Build debug apk

on:
 push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Make Gradle executable
      run: chmod +x ./gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Build debug APK
      run: ./gradlew assembleDebug
    - name: Authentication
      run: git remote set-url --push origin https://snikitin-de:$GITHUB_TOKEN@github.com/snikitin-de/Crypt-password
    - name: Adding new version of build
      uses: EndBug/add-and-commit@v2.1.0
      with:
         author_name: "Sergey Nikitin"
         author_email: "snikitin.de@gmail.com"
         message: "Обновление версии сборки приложения"
         path: "app/version.properties"
         pattern: "version.properties"
    - name: Releasing using Hub
      uses: snikitin-de/action-release-debugapk@master
      env:
       GITHUB_TOKEN: ${{ secrets.TOKEN }}
       APP_FOLDER: app
       RELEASE_TITLE: Отладочная версия
